#!/bin/bash
#
#SBATCH -t 24:00:00
#SBATCH -N 2048
#SBATCH -C knl,quad,cache
#SBATCH -o vpic.out11
#SBATCH -J ikink
#SBATCH -p regular
#SBATCH -A m2407     ## 3122
#SBATCH -L SCRATCH,project

###########DW persistentdw name=FFCOLL

########DW stage_in source=/global/cscratch1/sd/stanier/CURRENT-HEAD-VERSION/PRODUCTION-RUN/input destination=$DW_PERSISTENT_STRIPED_FFCOLL/input type=directory

#######DW stage_out source=$DW_PERSISTENT_STRIPED_FFCOLL/output destination=/global/cscratch1/sd/stanier/CURRENT-HEAD-VERSION/PRODUCTION-RUN/output type=directory


##### These are shell commands
date
module swap craype-haswell craype-mic-knl
module load lustre-default
module load dws
module list

#sbcast --compress --force --fanout=8 -t 240 ./untar.sh /tmp/untar.sh &  # Untar after stage in.
sbcast --compress --force --fanout=8 -t 240 ./sawtooth.Linux /tmp/sawtooth.Linux &
#sbcast --compress --force --fanout=8 -t 240 ./tar.sh /tmp/tar.sh &
wait

#cd $DW_JOB_STRIPED
##chmod +x ./ff-coll.Linux
##cd $DW_PERSISTENT_STRIPED_FFCOLL
#mkdir KNL64-PROP
#cd KNL64-PROP

export OMP_NUM_THREADS=32
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#Quad Cache:
time srun -n 16384 -N 2048 -c 32 --cpu_bind=cores /tmp/sawtooth.Linux --tpp 32 --restore restore0

date
echo 'Done'
